### ISSUE TITLE
tidy_proj fails with UnicodeEncodeError

### ISSUE THREAD

**Issue by luebbe** [joshkel/RadCli#1]
The exact error message is:

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 19653: ordinal not in range(128)`

In my case this was caused by German umlauts in the description in the Excluded_Packages section. I replaced the umlauts manually and tidy_proj worked. Since it is possible that the ide will insert non-ascii characters at any time into the dproj, it would be nice if tidy_proj could handle this.

A possible solution is to change line 125
`print(proj.toxml())`
to
`print(unicode(proj.toxml()).encode('utf8'))`

**Comment by joshkel** [comment]
Thanks for the bug report!

I just checked in a fix (based on your possible solution). Please let me know if you have any more problems.

**Comment by luebbe** [comment]
Thanks, works as expected now :)
